### ISSUE TITLE
Style definition for UL

### ISSUE THREAD

**Issue by AnsonSL** [craftcms/ckeditor#112]
### Description

Styles applied to lists and unordered lists using the styles plugin do not work.  This appears to be a bug in CK Editor that may have been fixed: https://github.com/ckeditor/ckeditor5/issues/14200

For example, I'm applying a larger font size to the paragraphs above and below a list. I'd like the list to also use a larger font size. I've setup a separate style for lists to apply a class that increases font size, but CK Editor removes the class. 

### Steps to reproduce

1. Select a list
2. Apply a style to the list

### Additional info

- Craft version: Craft CMS 4.4.11
- PHP version: 8.1.10
- Database driver & version: MYSQL 8.0.23
- Plugins & versions: "3.4.0",

**Comment by i-just** [comment]
Hi, thanks for reaching out.

Yes, you are right; this behaviour (or lack thereof) comes from the CKEditor.

The issue you linked to from the CKEditor repository was fixed in `v38.0.0`; however, the fix only applies to [`DocumentLists`](https://ckeditor.com/docs/ckeditor5/latest/features/lists/document-lists.html) and not [`Lists`](https://ckeditor.com/docs/ckeditor5/latest/features/lists/lists.html). 

Craft’s CKEditor plugin uses `Lists`, and only one of those two can be used. 

Only once [`To-do lists`](https://ckeditor.com/docs/ckeditor5/latest/features/lists/todo-lists.html) can work with `DocumentLists` (https://github.com/ckeditor/ckeditor5/issues/11620), we can consider switching to the `DocumentLists`. 

There’s also a chance this feature could be added by the CKEditor team to the `Lists`, as people are asking for it.

I hope the above helps!

**Comment by ansonleclair** [comment]
Thanks for looking into this. Is there a possibility that we could choose which list the plugin used through config?

**Comment by i-just** [comment]
Not a problem. We’ll discuss this internally, but it looks like a solution will come from CKEditor; just not sure when: https://github.com/ckeditor/ckeditor5/issues/14200#issuecomment-1625171318.

**Comment by brandonkelly** [comment]
CKEditor 3.5.0 is out with a new “List Plugin” setting :tada: (#122)

Note that the update requires [Craft 4.5.0](https://craftcms.com/blog/craft-4-5-released).
