### ISSUE TITLE
Live preview is not triggered when using panel features

### ISSUE THREAD

**Issue by debSource** [craftcms/ckeditor#172]
### Description
The live preview is not triggered when using features belonging to the panel. This are features such as:

- Format
- Styles
- Bold
- Italic
- Lists
- etc ...

### Steps to reproduce

1. Edit your text inside the CKEditor Field 
2. Add some panel features to the selected text such as bold, itelic, etc or add an image/list to the field

### Additional info
Adding images withing the CKEditor field does not trigger the reload of the live preview
Adding lists withing the CKEditor field does not trigger the reload of the live preview

- Craft version: 4.7.3
- PHP version: 8.1.7
- Database driver & version: MySQL 8.0.32
- Plugins & versions: CKEditor 3.7.3

**Comment by debSource** [comment]
Plugin has been updated today to **version 3.8.0**. The bug still persists.
![Screenshot 2024-02-22 133136](https://github.com/craftcms/ckeditor/assets/109602771/b8395194-a6b6-48f6-8bc5-fd737ac43fd2)
None of the panel features triggers a reload of the preview mode.

**Comment by i-just** [comment]
Hi, thanks for reaching out.

This happens because in Live Preview and when deciding whether to trigger the form’s autosave, in general, we listen to specific events and clicking on a button in the CKEditor field doesn’t trigger any of those events. If you were to click a Bold button and then, e.g. press an arrow key to move the cursor, or if you type anything in the field, the autosave will be triggered, and the preview will also get updated. 

I just raised a PR to improve this.

**Comment by brandonkelly** [comment]
This ended up being a Craft bug. Fixed in Craft 5.0.0-beta.7.
