### ISSUE TITLE
Nested entries aren't displayed for revisions

### ISSUE THREAD

**Issue by mmikkel** [craftcms/ckeditor#227]
### Description

When viewing a revision, nested entries inside CKEditor fields are not visible.

![CleanShot 2024-05-06 at 11 02 15@2x](https://github.com/craftcms/ckeditor/assets/298510/c37b82dd-b721-4078-a912-463a41facd21)

![CleanShot 2024-05-06 at 11 02 32@2x](https://github.com/craftcms/ckeditor/assets/298510/791503c2-ce2c-4eb1-9892-73700c429c6b)

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 5.1.1
- PHP version:
- Database driver & version:
- Plugins & versions: CKEditor v. 4.0.4

**Comment by i-just** [comment]
Hi, thanks for getting in touch! I’m not able to replicate this under standard circumstances.

The only way I can trigger this behaviour is if I add a nested entry to the CKE and save (revision 1), remove the nested entry, add a different one and save (revision 2), run garbage collection, and then view the first revision. This is consistent with what happens to other nested entries (e.g. inside a matrix field). That being said, this probably isn’t the expected behaviour.

I’m transferring this to the cms repo and we'll work on a solution.

**Comment by brandonkelly** [comment]
Fixed in CKEditor 4.0.5!
